# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcb620269f62be4965c9b24f2ef719fdbecca033f8b98a2cc8c2b97b0bd0779e7786c2397236f8b153c5c5c536c1238435d86bbde8d2c8e8c6a40499d8dea09

test:
  secret_key_base: 913597493486c3f2021891c9d2419b14495258366f8e45f832a7e89a6856502d75c779771947c182b73c60fab090895f495b444bb6210e1d0d892c86d3b3a8dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
